CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    role VARCHAR(50) NOT NULL,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    vk_id BIGINT,
    enabled BOOLEAN DEFAULT TRUE,
    provider VARCHAR(50) NOT NULL,
    email VARCHAR(255),
    birth_date DATE,
    age INTEGER,
    gender VARCHAR(10),
    city VARCHAR(255),
    job VARCHAR(255),
    education VARCHAR(255),
    about_me TEXT,
    theme VARCHAR(255) NOT NULL,
    telegram_id VARCHAR(255)
);

CREATE TABLE photos (
    id SERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    path TEXT NOT NULL
);

CREATE TABLE interests (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    color VARCHAR(7) NOT NULL,
    textColor VARCHAR(7) NOT NULL
);

CREATE TABLE user_interests (
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    interest_id BIGINT NOT NULL REFERENCES interests(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, interest_id)
);

CREATE TABLE user_coordinates (
    id SERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    city VARCHAR(255) NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL
);
CREATE TABLE user_filters (
                              id BIGSERIAL PRIMARY KEY,
                              user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                              min_age INT NOT NULL,
                              max_age INT NOT NULL,
                              gender_filter VARCHAR(255) NOT NULL,
                              search_radius INT NOT NULL,
                              UNIQUE (user_id)
);
-- likes table
CREATE TABLE likes (
                       id BIGSERIAL PRIMARY KEY,
                       first_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                       second_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                       type_of_like SMALLINT NOT NULL CHECK (type_of_like IN (1, 2, 3)),
                       created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


-- matches table
CREATE TABLE matches (
                         id BIGSERIAL PRIMARY KEY,
                         user_id1 BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                         user_id2 BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                         created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO interests (name, color, textColor) VALUES
                                                   ('Рисование', '#D1E9F6', '#50819B'),
                                                   ('Фотография', '#D1E9F6', '#50819B'),
                                                   ('Видеоигры', '#D1E9F6', '#50819B'),
                                                   ('Чтение', '#D1E9F6', '#50819B'),
                                                   ('Писательство', '#D1E9F6', '#50819B'),
                                                   ('Кулинария', '#D1E9F6', '#50819B'),
                                                   ('Рукоделие', '#D1E9F6', '#50819B'),
                                                   ('Вязание', '#D1E9F6', '#50819B'),
                                                   ('Садоводство', '#D1E9F6', '#50819B'),
                                                   ('Рыбалка', '#D1E9F6', '#50819B'),
                                                   ('Охота', '#D1E9F6', '#50819B'),
                                                   ('Коллекционирование', '#D1E9F6', '#50819B'),
                                                   ('Музыка', '#D1E9F6', '#50819B'),
                                                   ('Вокал', '#D1E9F6', '#50819B'),
                                                   ('Игра на гитаре', '#D1E9F6', '#50819B'),
                                                   ('Игра на пианино', '#D1E9F6', '#50819B'),
                                                   ('Виноделие', '#D1E9F6', '#50819B'),
                                                   ('Йога', '#D1E9F6', '#50819B'),
                                                   ('Танцы', '#D1E9F6', '#50819B'),
                                                   ('Бег', '#FFEAD6', '#CC7A33'),
                                                   ('Велосипед', '#FFEAD6', '#CC7A33'),
                                                   ('Плавание', '#FFEAD6', '#CC7A33'),
                                                   ('Фитнес', '#FFEAD6', '#CC7A33'),
                                                   ('Бокс', '#FFEAD6', '#CC7A33'),
                                                   ('Серфинг', '#FFEAD6', '#CC7A33'),
                                                   ('Футбол', '#FFEAD6', '#CC7A33'),
                                                   ('Баскетбол', '#FFEAD6', '#CC7A33'),
                                                   ('Волейбол', '#FFEAD6', '#CC7A33'),
                                                   ('Теннис', '#FFEAD6', '#CC7A33'),
                                                   ('Катание на лыжах', '#FFEAD6', '#CC7A33'),
                                                   ('Скалолазание', '#FFEAD6', '#CC7A33'),
                                                   ('Паркур', '#FFEAD6', '#CC7A33'),
                                                   ('Туризм', '#FFEAD6', '#CC7A33'),
                                                   ('Альпинизм', '#FFEAD6', '#CC7A33'),
                                                   ('Гольф', '#FFEAD6', '#CC7A33'),
                                                   ('Пилатес', '#FFEAD6', '#CC7A33'),
                                                   ('Сноуборд', '#FFEAD6', '#CC7A33'),
                                                   ('Катание на коньках', '#FFEAD6', '#CC7A33'),
                                                   ('Гребля', '#FFEAD6', '#CC7A33'),
                                                   ('Документальные фильмы', '#E9D1F6', '#81509B'),
                                                   ('Триллеры', '#E9D1F6', '#81509B'),
                                                   ('Фантастика', '#E9D1F6', '#81509B'),
                                                   ('Комедии', '#E9D1F6', '#81509B'),
                                                   ('Драмы', '#E9D1F6', '#81509B'),
                                                   ('Боевики', '#E9D1F6', '#81509B'),
                                                   ('Аниме', '#E9D1F6', '#81509B'),
                                                   ('Сериалы', '#E9D1F6', '#81509B'),
                                                   ('Короткометражки', '#E9D1F6', '#81509B'),
                                                   ('Мультфильмы', '#E9D1F6', '#81509B'),
                                                   ('Биографические фильмы', '#E9D1F6', '#81509B'),
                                                   ('Исторические фильмы', '#E9D1F6', '#81509B'),
                                                   ('Музыкальные шоу', '#E9D1F6', '#81509B'),
                                                   ('Робототехника', '#D1D8F6', '#50679B'),
                                                   ('Искусственный интеллект', '#D1D8F6', '#50679B'),
                                                   ('Виртуальная реальность', '#D1D8F6', '#50679B'),
                                                   ('Космос', '#D1D8F6', '#50679B'),
                                                   ('Программирование', '#D1D8F6', '#50679B'),
                                                   ('Биотехнологии', '#D1D8F6', '#50679B'),
                                                   ('Астрономия', '#D1D8F6', '#50679B'),
                                                   ('Нанотехнологии', '#D1D8F6', '#50679B'),
                                                   ('Гаджеты', '#D1D8F6', '#50679B'),
                                                   ('Научные открытия', '#D1D8F6', '#50679B'),
                                                   ('Инженерия', '#D1D8F6', '#50679B'),
                                                   ('Автомобили', '#D1D8F6', '#50679B'),
                                                   ('Авиация', '#D1D8F6', '#50679B'),
                                                   ('Видеоблоги', '#D1D8F6', '#50679B'),
                                                   ('Путешествия', '#F6EBD1', '#9B7F50'),
                                                   ('Экзотические страны', '#F6EBD1', '#9B7F50'),
                                                   ('Кулинарные туры', '#F6EBD1', '#9B7F50'),
                                                   ('Автопутешествия', '#F6EBD1', '#9B7F50'),
                                                   ('Кемпинг', '#F6EBD1', '#9B7F50'),
                                                   ('Путешествия по Европе', '#F6EBD1', '#9B7F50'),
                                                   ('Национальные парки', '#F6EBD1', '#9B7F50'),
                                                   ('Горы', '#F6EBD1', '#9B7F50'),
                                                   ('Пляжи', '#F6EBD1', '#9B7F50'),
                                                   ('Города', '#F6EBD1', '#9B7F50'),
                                                   ('Культура разных стран', '#F6EBD1', '#9B7F50'),
                                                   ('Архитектура', '#F6EBD1', '#9B7F50'),
                                                   ('Языки', '#F6EBD1', '#9B7F50'),
                                                   ('Поэзия', '#F6D1D8', '#9B5057'),
                                                   ('Литература', '#F6D1D8', '#9B5057'),
                                                   ('Классическая музыка', '#F6D1D8', '#9B5057'),
                                                   ('Скульптура', '#F6D1D8', '#9B5057'),
                                                   ('Театр', '#F6D1D8', '#9B5057'),
                                                   ('Кинематограф', '#F6D1D8', '#9B5057'),
                                                   ('Искусствоведение', '#F6D1D8', '#9B5057'),
                                                   ('Модернизм', '#F6D1D8', '#9B5057'),
                                                   ('Постмодернизм', '#F6D1D8', '#9B5057'),
                                                   ('Барокко', '#F6D1D8', '#9B5057'),
                                                   ('Импрессионизм', '#F6D1D8', '#9B5057'),
                                                   ('Граффити', '#F6D1D8', '#9B5057'),
                                                   ('Художественные галереи', '#F6D1D8', '#9B5057'),
                                                   ('Здоровое питание', '#D1F6E3', '#509B7F'),
                                                   ('Вегетарианство', '#D1F6E3', '#509B7F'),
                                                   ('Веганство', '#D1F6E3', '#509B7F'),
                                                   ('Медитация', '#D1F6E3', '#509B7F'),
                                                   ('Психология', '#D1F6E3', '#509B7F'),
                                                   ('Осознанность', '#D1F6E3', '#509B7F'),
                                                   ('Кинезитерапия', '#D1F6E3', '#509B7F'),
                                                   ('ЗОЖ', '#D1F6E3', '#509B7F'),
                                                   ('Диетология', '#D1F6E3', '#509B7F'),
                                                   ('Сон', '#D1F6E3', '#509B7F'),
                                                   ('Йога', '#D1F6E3', '#509B7F'),
                                                   ('Альтернативная медицина', '#D1F6E3', '#509B7F'),
                                                   ('Саморазвитие', '#D1F6E3', '#509B7F'),
                                                   ('Вино', '#F6ECD1', '#9B8650'),
                                                   ('Кофе', '#F6ECD1', '#9B8650'),
                                                   ('Чай', '#F6ECD1', '#9B8650'),
                                                   ('Выпечка', '#F6ECD1', '#9B8650'),
                                                   ('Сыр', '#F6ECD1', '#9B8650'),
                                                   ('Вегетарианские блюда', '#F6ECD1', '#9B8650'),
                                                   ('Мясные блюда', '#F6ECD1', '#9B8650'),
                                                   ('Молекулярная кухня', '#F6ECD1', '#9B8650'),
                                                   ('Коктейли', '#F6ECD1', '#9B8650'),
                                                   ('Экзотические блюда', '#F6ECD1', '#9B8650'),
                                                   ('Морепродукты', '#F6ECD1', '#9B8650'),
                                                   ('Уличная еда', '#F6ECD1', '#9B8650'),
                                                   ('Гастрономические фестивали', '#F6ECD1', '#9B8650'),
                                                   ('Кошки', '#F6DCD1', '#9B6650'),
                                                   ('Собаки', '#F6DCD1', '#9B6650'),
                                                   ('Лошади', '#F6DCD1', '#9B6650'),
                                                   ('Рыбки', '#F6DCD1', '#9B6650'),
                                                   ('Рептилии', '#F6DCD1', '#9B6650'),
                                                   ('Попугаи', '#F6DCD1', '#9B6650'),
                                                   ('Кролики', '#F6DCD1', '#9B6650'),
                                                   ('Хомяки', '#F6DCD1', '#9B6650'),
                                                   ('Экзотические питомцы', '#F6DCD1', '#9B6650'),
                                                   ('Фермерские животные', '#F6DCD1', '#9B6650'),
                                                   ('Аквариумистика', '#F6DCD1', '#9B6650'),
                                                   ('Иностранные языки', '#E1D1F6', '#75509B'),
                                                   ('Самообразование', '#E1D1F6', '#75509B'),
                                                   ('Лидерство', '#E1D1F6', '#75509B'),
                                                   ('Креативность', '#E1D1F6', '#75509B'),
                                                   ('Бизнес', '#E1D1F6', '#75509B'),
                                                   ('Маркетинг', '#E1D1F6', '#75509B'),
                                                   ('Личностный рост', '#E1D1F6', '#75509B'),
                                                   ('Психология', '#E1D1F6', '#75509B'),
                                                   ('Карьера', '#E1D1F6', '#75509B'),
                                                   ('Ораторское искусство', '#E1D1F6', '#75509B'),
                                                   ('Публичные выступления', '#E1D1F6', '#75509B'),
                                                   ('Тайм-менеджмент', '#E1D1F6', '#75509B'),
                                                   ('Коучинг', '#E1D1F6', '#75509B'),
                                                   ('Лайфхаки', '#E1D1F6', '#75509B');
